### PR TITLE
Added argparse module implementation

### PR DESCRIPTION
**Pull request by alt-glitch**

### CODE REVIEW

**Comment by EONRaider** [comment]
It's a good implementation of argparse but as stated in the README I decided not to use it in order to keep it as close as possible to the code in the book (which is terrible, I know). The purpose if this particular repository is to serve as a reference for people while reading the book.

**Comment by alt-glitch** [comment]
> It's a good implementation of argparse but as stated in the README I decided not to use it in order to keep it as close as possible to the code in the book (which is terrible, I know). The purpose if this particular repository is to serve as a reference for people while reading the book.

Understandable. This gives me an idea for a new repository I suppose. BlackHat Python3 with code improvements! What are your thoughts? I have just started reading the book so I'm exploring ways to apply the knowledge.

**Comment by EONRaider** [comment]
You can definitely learn a lot by doing that. There's a lot of room for improvement in the code.

**Comment by alt-glitch** [comment]
Great! Thanks for the input!

**Pull request closed without merging**
